server:
  servlet:
    context-path: /qbrainx-website
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qbrainx
    username: postgres
    password: Sangi@123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
springdoc:
  group-configs:
    - group: qbrainx-website
      packagesToScan:
        - "com.qbrainx"
  swagger-ui:
    path: /qbrainx-1336586310L-swagger-ui.html
  api-docs:
    path: /v3/qbrainx-1336586310L-api-docs